FROM openjdk:8-jdk

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git clone --branch master https://github.com/KA226-COVID/exercises-storage.git

WORKDIR /app/exercises-storage

RUN chmod +x mvnw

EXPOSE 8080

ENTRYPOINT [ "./mvnw", "spring-boot:run" ]
