FROM node:14.18
ARG GITHUB_TOKEN=${GITHUB_TOKEN}

RUN apt-get update

RUN apt-get install -y git

WORKDIR /app

RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

RUN git clone --branch master https://github.com/KA226-COVID/xml-evaluator.git

WORKDIR /app/xml-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "prod" ]
